# change the followings to match your Github username and repo name
baseurl: "/jekyll-project-template" # the name of your github repo
url: "https://BCDigSchol.github.io" # the url of your github pages (change BCDigSchol to your username)

# site information used in page title, meta data etc.
title: "On the Edge of Revolution"
description: Loyalties in Revolutionary Gerogia 

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: History
    submenu:
      - title: Revolutionary Georgia
        link: background
      - title: American Loyalists
        link: Aloyalists
  - title: Projects 
    submenu:
      - title: Georgia Loyalists
        link: Gloyalists 
      - title: Trade Connections
        link: trade 
  - title: About
    submenu:
      - title: About the Project 
        link: Project 
      - title: Bibliography
        link: bibliography 
     

# sets whether a search bar appears on the site header
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: [CC BY-NC License](https://creativecommons.org/licenses/by-nc/4.0/deed.en)
footer-submessage:  Garrett Howe, with the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
